### ISSUE TITLE
Corregir errores de accesibilidad y seguridad

### ISSUE THREAD

**Issue by ricardoerl** [horchatajs/website#33]
**Descripción del error**
Usando la herramienta [webhint.io](https://webhint.io/) aparecen varios errores de accesibilidad, rendimiento y seguridad que se pueden resolver.

**Comportamiento esperado**
No recibir ningún error (o la menor cantidad posible) usando la herramienta de webhint.

**Pasos para reproducir el error**
Visitar el reporte (o volver a realizarlo) aquí: https://webhint.io/scanner/9330eecb-07c7-4643-9ff9-4a28e84dedbc

**Comment by Stanley-Jovel** [comment]
I'm on it

**Comment by ricardoerl** [comment]
Seria bueno dividir las tareas para saber los avances y no hacer todo en un solo cambio.
