### ISSUE TITLE
Arreglar menú en móvil

### ISSUE THREAD

**Issue by ricardoerl** [horchatajs/website#34]
**Descripción del error**
El menú en dispositivos móviles queda activado al navegar entre páginas del sitio.

**Comportamiento esperado**
Al probar el sitio móvil, el menú debe volver a su estado original (escondido) cada vez que el usuario cambie de página.

**Pasos para reproducir el error**
1.  Visitar el sitio en un móvil (o probar desde herramienta de desarrollo móvil).
2.  Hacer click en el menú.
3.  Hacer click en 'Blog'

**Detalles de entorno**
https://mybrowser.fyi/report/5b7512476e6d49001430a833

**Información adicional**
Tal vez se puede considerar usar alguna librería para menús móviles ya disponble.

**Comment by diedu89** [comment]
Solo para links internos o también lo escondemos para los de fb, tw, etc?
