### ISSUE TITLE
Implementar guía de estilo del código para el proyecto

### ISSUE THREAD

**Issue by ricardoerl** [horchatajs/website#48]
**Descripción de la idea/sugerencia**
Como proyecto comunitario de debería tener una guía de estilos que permita mantener la consistencia de las contribuciones que se vayan aceptado.

Entiendo que incluir este tipo de sugerencia podría cambiar parte del código ya existente. Lo anterior no creo que sea problema en la medida que beneficie a futuro las nuevas contribuciones.

Seria interesante evaluar ejemplos de otros proyectos que sigan una guía de estilo o posibles mejores prácticas.

**Comment by gfranco93** [comment]
Creo que lo mejor seria adoptar un estilo ya existente, como por ejemplo la [guía de estilo de airbnb](https://github.com/airbnb/javascript). Si están de acuerdo puedo crear un PR.

**Comment by cesaramirez** [comment]
Claro, esa es la idea, creo que esta un poco confuso el titulo del issue, esperamos tu PR @gfranco93.

**Comment by ricardoerl** [comment]
> Creo que lo mejor seria adoptar un estilo ya existente, como por ejemplo la [guía de estilo de airbnb](https://github.com/airbnb/javascript). Si están de acuerdo puedo crear un PR.

Si, airbnb me parece bien.

**Comment by gfranco93** [comment]
Perfecto, cuando lo tenga terminado lo subo

**Comment by juan-carlos-correa** [comment]
@ricardoerl agregué PR con una propuesta de guía de estilos usando standard js para que puedas ver también cómo sería con esta otra alternativa. 

Airbnb es popular también, qué mejor que conocer diferentes guías ;D

**Comment by ricardoerl** [comment]
@Physsi07 y @juan-carlos-correa gracias por su contribución.

En lo personal preferiría implementar _airbnb_ sobre _stardard_, considero que tiene más reglas que son de mi gusto (trailing comma, semicolons, etc). 

Pero soy consiente que es subjetivo, me gustaría escuchas sus opiniones. ¿@cesaramirez, que decís?

**Comment by Physsi07** [comment]
Tienes que tratar dejar de utilizar muchas librerias, porque en un largo plazo cuando tu projecto se comiense a poner mas y mas grande te va a perjudicar, ya tienes bootstrap incluido que coje un monton de espacio y es bien pesado, so no recomiendo que usa tantas librerias. no creo que solo por textos y tamanos de texto, eso es facil de solucionar con CSS. Aveces si hay que hacerce la vida mas facil pero no con pequeneses asi.

**Comment by cesaramirez** [comment]
@ricardoerl en este caso me parece ideal implementar _airbnb_, me parecen más adecuadas las reglas que esta guía de estilo sugiere.

Por otro lado @Physsi07 considero que no se están utilizando tantas librerías, la mayoría forma parte del core de Gatsby, para css utilizamos **Bulma** que es un framework muy ligero y potente y que estudiándolo bien nos brinda una solución para la corrección de los tamaños de texto.
